version: "3"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.${COMPUTE_UNIT}
    container_name: openai_fastapi_container
    environment:
      OPENAI_API_TYPE: ${OPENAI_API_TYPE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_ENDPOINT: ${OPENAI_API_ENDPOINT}
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_COLLECTION: ${MONGODB_COLLECTION}
    volumes:
      - ./main.py:/app/main.py
    ports:
      - "80:8000"

  mongodb:
    image: mongo:4.4.9
    container_name: mongodb_container
    ports:
      - "127.0.0.1:27017:27017"
